### ISSUE TITLE
Templates & Features

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/IDES-2015#1]
## Templates
Homepage (flex content, 2 latest posts, apply banner, social feed)
Regular page (flex content, apply banner, social feed)
Faculty archive (custom posts)
Alumni archive (custom posts)
Gallery
News archive

## Features
Social feed (maybe a checkbox?)
Search
Slider (built in to flex content)
Apply banner (maybe a checkbox?)

## Grid
1 col, 2 col, 3 col, 4 col

**Comment by streeetlamp** [comment]
Will the gallery just be a stream of images from everywhere or does it need to be divided into people, categories, etc? 

Sitemap and wireframe: https://slack-files.com/files-pri-safe/T02B4RG46-F0C03HZJ6/wireframe-6-gallery.pdf?c=1448292535-f6e381a575f6c7bd99e52908501dd09e9a8656b4

https://slack-files.com/files-pri-safe/T02B4RG46-F0BTCLU7J/interiordesign-sitemap.pdf?c=1448292538-6814d4c516d2c4d948187b5ec6d10622d2507d68

**Comment by dstrogiy** [comment]
I think they wanted one big gallery with everything in it, I'll double check

**Comment by dstrogiy** [comment]
Yep, "one big gallery with captions"
