### ISSUE TITLE
gallery page

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/IDES-2015#13]

**Comment by dstrogiy** [comment]
Should we do masonry?

**Comment by dstrogiy** [comment]
In progress

**Comment by dstrogiy** [comment]
- [ ] needs yellow overlay on hover 
- [ ] needs to be responsive
- [ ] could use a transition when opening (maybe like on http://arts.vcu.edu/kineticimaging/galleries/)
- [ ] captions are not the best looking
- [ ] arrows should be angles instead (I think)

**Comment by streeetlamp** [comment]
![popkey-i_dont_be](https://cloud.githubusercontent.com/assets/1740634/11880291/f01ea0ba-a4cd-11e5-83d9-3e2f844ff75a.gif)
