### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/IDES-2015#15]
![search-1](https://cloud.githubusercontent.com/assets/6132788/11689661/f63ad518-9e60-11e5-8b94-ce3baf0c43d3.gif)

**Comment by PeytonSorah** [comment]
@dstrogiy Do you think that the search button should be somewhere other than in the footer? As is, it's a little bit hard to find.

**Comment by dstrogiy** [comment]
I'm not really concerned with it, since I don't think people use search, but we can definitely stick it somewhere else if you guys think it should be done.

**Comment by streeetlamp** [comment]
should be aight, open new issues for new search bugs
