### ISSUE TITLE
Template Part (?) to exit out of content wrapper

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/IDES-2015#3]
At the moment most of page templates are set up to house all of the content inside a max-width wrapper. We need to be able to have full screen width areas, such as the slider and content blocks on most pages.

Here's what I have right now for the slider module:

    </section>
    </article>
    </main>
    </div>
    </div>

    //slider code

    <div class="content">
    <div class="inner-content">
    <main class="main">
    <article>
    <section class="entry-content">

We should have a more elegant way to do that.

**Comment by streeetlamp** [comment]
fixed here 0f106f47c96e6ab60f41a1be40439c48e4ca97ed
just need to wrap individual groups of elements that need a wrap now
