### ISSUE TITLE
Misc. Edits from Rob 1/29

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/IDES-2015#39]
- [x] Apply Now - too minimal, maybe bring color back just without pattern 
- [x] http://arts.vcu.edu/interiorde2015/academics/ links to sub pages should be more prominent (maybe 3 columns with each link being a colored box or image kinda thing)
- [x] Resources page more visual like other pages ( http://arts.vcu.edu/interiorde2015/about/ for example )
- [x] Contact form should go to intdesign@vcu.edu

**Comment by dstrogiy** [comment]
I think all of these are taken care of.

**Comment by streeetlamp** [comment]
![tumblr_inline_o1qf45lmdn1r79k32_500](https://cloud.githubusercontent.com/assets/1740634/12725311/20bffaa8-c8e0-11e5-8def-1b561931a4f3.gif)
