### ISSUE TITLE
General Edits: Feb 17

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/IDES-2015#40]
- [x] make sure all color boxes and images are contained within the grid
- [x] give apply now a solid background (pale yellow or gray) and stretch to edges
- [x] introductory material on home page under slider
- [x] left align subnav to the Interior Design logo
- [x] make sure images do not have white backgrounds 
- [x] make sure all links open in new tab
- [x] give each section on academic overview page its own row and overview text 
- [x] black band is too heavy-break the two paragraphs into their own row w/ pic
- [x] make height of blog posts the same across the board-the read more should never run underneath the image
- [x] change "IDES" to "VCU Interior Design" above social
- [x] minimize white space throughout
- [x] add Rob as user
- [x] tertiary nav covering text-come up with alternative

**Comment by dstrogiy** [comment]
We just need to add Rob and I think we good
